[CHARACTER]
XML1_num = 0001
XML2_num = 0001
MUA1_num = 0001
MUA2_num = 0001
XML1_path = Detect
XML2_path = Detect
MUA1_path = Detect
MUA2_path = Detect

[ASSET]
XML1_num_XX = True
XML2_num_XX = True
MUA1_num_XX = True
MUA2_num_XX = True
XML1_special_name = None
XML2_special_name = None
MUA1_special_name = None
MUA2_special_name = None

[CONSOLES]
PC = True
Steam = True
GameCube = True
PS2 = True
PS3 = True
PSP = True
Wii = True
Xbox = True
Xbox_360 = True

[SETTINGS]
big_texture = True
secondary_skin = True
untextured_okay = False
generate_collision = False
igBlend_to_igAlpha_transparency = False
skip_subfolder = False
force_adv_tex_folders = False
advanced_texture_ini = None
forced_asset_type = None
;debug_mode = True