[CHARACTER]
XML1_num = 0001
XML2_num = 0001
MUA1_num = 0001
MUA2_num = 0001
XML1_path = None
;XML1_path = C:\Github\BaconWizard17-Mod-Releases\Custom Models - XML1, XML2\Defaultman\6. Metal Form
XML2_path = None
;XML2_path = C:\Github\BaconWizard17-Mod-Releases\Custom Models - XML1, XML2\Defaultman\6. Metal Form
;MUA1_path = None
MUA1_path = C:\Github\BaconWizard17-Mod-Releases\Custom Models - MUA1, MUA2\Defaultman\6. Metal Form
MUA2_path = None
;MUA2_path = C:\Github\BaconWizard17-Mod-Releases\Custom Models - MUA1, MUA2\Defaultman\6. Metal Form

[ASSET]
XML1_num_XX = True
XML2_num_XX = True
MUA1_num_XX = True
MUA2_num_XX = True
XML1_special_name = None
XML2_special_name = None
MUA1_special_name = None
MUA2_special_name = None

[CONSOLES]
PC = True
Steam = True
GameCube = False
PS2 = False
PS3 = True
PSP = False
Wii = False
Xbox = False
Xbox_360 = True

[SETTINGS]
big_texture = True
secondary_skin = True
untextured_okay = False
generate_collision = False
igBlend_to_igAlpha_transparency = False
skip_subfolder = False
force_adv_tex_folders = False
advanced_texture_ini = C:\Github\BaconWizard17-Custom-Models\Characters\Defaultman\Skins\Metal Form\NextGenOpt.ini
forced_asset_type = None
debug_mode = True